services:
  service-scheduler:
    build:
      context: ../../backend
      dockerfile: services/scheduler/.cloud/docker/Dockerfile
      target: plugin-dev
      args:
        - PLUGINNAME=scheduler
        - KIND=services
    image: codeclarityce/service-scheduler-dev:latest
    restart: always
    volumes:
      - ../../backend:/codeclarity
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_started
      pg_bouncer:
        condition: service_started
      adminer:
        condition: service_started
    env_file:
      - ../../.cloud/env/.env.dev