# syntax=docker/dockerfile:1

ARG KIND=services
ARG USERNAME=codeclarity
ARG PLUGINNAME=scheduler

# DEV IMAGE
FROM golang:1.27.1-alpine@sha256:cf6fca6641884b8433441b2b0652976f975e1d0fdd26d177eaaf8596087f3125 AS plugin-dev
ARG KIND
ARG PLUGINNAME
WORKDIR /codeclarity/${KIND}/${PLUGINNAME}
ADD .cloud/docker/config/* /root
RUN apk add git
RUN go install github.com/air-verse/air@v1.64.5
CMD ["air", "-c", ".air.toml"]

# DEBUG IMAGE
FROM golang:1.27.1-alpine@sha256:cf6fca6641884b8433441b2b0652976f975e1d0fdd26d177eaaf8596087f3125 AS plugin-debug
ARG KIND
ARG PLUGINNAME
ENV KIND=${KIND}
ENV PLUGINNAME=${PLUGINNAME}
RUN apk add git
RUN go install github.com/go-delve/delve/cmd/dlv@latest
ADD .cloud/docker/config/* /root
WORKDIR /codeclarity/${KIND}/${PLUGINNAME}
CMD ["/go/bin/dlv", "debug", ".", "--headless", "--listen=:40000", "--accept-multiclient"]
# CMD tail -f /dev/null


# BUILD IMAGE
FROM golang:1.27.1-alpine@sha256:cf6fca6641884b8433441b2b0652976f975e1d0fdd26d177eaaf8596087f3125 AS plugin-build
ARG KIND
ARG PLUGINNAME
ARG DIRNAME=
COPY . /codeclarity_src
RUN DIR="${DIRNAME:-${PLUGINNAME}}" && \
    if [ -d "/codeclarity_src/${KIND}/$DIR" ]; then \
      mv /codeclarity_src /codeclarity; \
      if [ "$DIR" != "${PLUGINNAME}" ]; then \
        ln -s "$DIR" "/codeclarity/${KIND}/${PLUGINNAME}"; \
      fi; \
    else \
      mkdir -p /codeclarity/${KIND} && \
      mv /codeclarity_src /codeclarity/${KIND}/${PLUGINNAME} && \
      rm -f /codeclarity/${KIND}/${PLUGINNAME}/go.work; \
    fi
WORKDIR /codeclarity/${KIND}/${PLUGINNAME}
RUN apk update && apk upgrade --no-cache
RUN apk add git
RUN [ "go", "build", "-o", "scheduler" ]

# PRODUCTION IMAGE
FROM alpine:3.24.0@sha256:a2d49ea686c2adfe3c992e47dc3b5e7fa6e6b5055609400dc2acaeb241c829f4 AS plugin
ARG KIND
ARG USERNAME
ARG PLUGINNAME
RUN adduser -D ${USERNAME}
USER ${USERNAME}
WORKDIR /home/${USERNAME}/${PLUGINNAME}
COPY --from=plugin-build --chown=codeclarity:codeclarity /codeclarity/${KIND}/${PLUGINNAME}/scheduler .
COPY --from=plugin-build --chown=codeclarity:codeclarity /codeclarity/${KIND}/${PLUGINNAME}/config.json .

RUN mkdir /home/${USERNAME}/private

ENTRYPOINT [ "./scheduler" ]